### ISSUE TITLE
SBHub will feature an events section

### ISSUE THREAD

**Issue by dwcaraway** [18F/afsmallbiz#32]
There is a need to "advertise" upcoming events of interest to the SB community. In most cases they would then click on a link that takes them to another organization's web site for more info or to register. An example: OAI (Ohio Aerospace Institute) will offer a SBIR/STTR Workshop at Tec^Edge on August 14th.Proposal Preparation for DoD

**Comment by dwcaraway** [comment]
@lesmcfawn How about putting a feed from a Google Calendar on the site? Would make editing/maintaining data pretty straightforward (looks like WBI already uses a Google Calendar for scheduling things)

**Comment by lesmcfawn** [comment]
David,

Good idea. Lets give it a try.

Les

**Comment by dwcaraway** [comment]
@lesmcfawn I uploaded a preview of the events display on a separate page. Would love to get your thoughts when you have a moment: http://sbhub.wbi-icc.com/events.html

**Comment by dwcaraway** [comment]
@lesmcfawn just got confirmation that folks on DoD NIPR are able to view the calendar, though they weren't able to see the data from the API feed (bulleted items at bottom of page)

**Comment by lesmcfawn** [comment]
Dave,

The Google calendar is nice. Stop by tomorrow if you have a chance so we can chat about this.

Les

**Comment by dwcaraway** [comment]
Sure thing
