### ISSUE TITLE
Start index parameter

### ISSUE THREAD

**Issue by dwcaraway** [18F/afsmallbiz#48]
A user may specify a starting index for returned results.

The start parameter specifies the index of the first matching result that should be included in the result set. This parameter uses a one-based index, meaning the first result is 1, the second result is 2 and so forth. This parameter works in conjunction with the limit parameter to determine which results to return. For example, to request the second set of 10 results – i.e. results 11-20 – set the start parameter to 11 and the limit parameter to 10.

**Comment by catherinedevlin** [comment]
How should this relate to the "page" parameter as it's now written into lib/controllers/api.js?  Should it support both "page" and "start"?

**Comment by dwcaraway** [comment]
Let's go with both "page" and "start"  -- page is good for user interfaces, start for automation / machines. Looking at google search results, look like they have a page and start as well.
![google search results](https://www.evernote.com/shard/s218/sh/5aee9f38-a43f-4a47-b26e-a1056f1939ba/1c6b827bf49d133fbbf22dab1af133e5/res/95432088-2a95-4a38-b14e-bfd791204885/skitch.png?resizeSmall&width=832)
