### ISSUE TITLE
Replace "year" parameter with "date" parameter

### ISSUE THREAD

**Issue by dwcaraway** [18F/afsmallbiz#51]
NAICS information is returned for a specific date (date parameter in YYYYMMDD format). By default, NAICS information is returned for current date.

For example, given a naics of 21113 and a date of 20080412, return the matching naics description for 2007.

**Comment by catherinedevlin** [comment]
- Continue to support `year` parameter?
  - If `year` and `date` conflict, throw an error?

**Comment by dwcaraway** [comment]
I'd remove the `year` parameter altogether. It's confusing. 

If date is omitted, use the NAICS year closest the current date (e.g. 2012).

If date is before earliest naics year in the database (currently 2007), return an error.
