### ISSUE TITLE
Contractor search

### ISSUE THREAD

**Issue by dwcaraway** [18F/afsmallbiz#52]
(Placeholder) Make it easy to discover procurement contractors.

See notes:
https://www.sam.gov/portal/SAM/?navigationalstate=JBPNS_rO0ABXdcACJqYXZheC5mYWNlcy5wb3J0bGV0YnJpZGdlLlNUQVRFX0lEAAAAAQApdmlldzowZGIyOThkNy05MTUyLTQxZjgtYjI1My1jM2E5M2ZkMTJiZWEAB19fRU9GX18*&portal:componentId=55361dcd-5ed2-4706-8f0b-849ef8ec9de2&interactionstate=JBPNS_rO0ABXdBABBfanNmQnJpZGdlVmlld0lkAAAAAQAgL2pzZi9leHRyYWN0cy9zYW1FeHRyYWN0c05hdi5qc3AAB19fRU9GX18*&portal:type=action##11

sam.gov -> data access -> em extracts (left sidebar) --> midway down the page, Legacy CCR Extracts Public FOIA package

there's a monthly file there
so the link is small and says May 2014 right now

**Comment by catherinedevlin** [comment]
Links to "June 2014" and "July 2014" are the same URL, maybe they just failed to delete June:
https://www.sam.gov/public-extracts/CCR-FOIA/CCR_FOIA_Extract.zip
https://www.sam.gov/public-extracts/CCR-FOIA/CCR_FOIA_Extract.zip

**Comment by dwcaraway** [comment]
I think so. Their URL structure indicates that they don't support more than the current month's extract

**Comment by catherinedevlin** [comment]
So, each contractor has a set of NAICS codes it corresponds to - is that how it should be discoverable, with a "contractor" field analogous to the "crossrefs" field (in that it displays the set of corresponding child records)?  

How much data from this do we want to expose?  There's 148 ugly, ugly fields; of course, most of those could be lumped up for display (eight fields for contact info for PREV BUS, eight for GOV BUS, eight for PREVIOUS GOV BUS, etc.)  

This dataset positively reeks of COBOL.  Just saying.

**Comment by dwcaraway** [comment]
The initial intent is to have small businesses able to discover partners for pursuing larger contract opportunities or to perform market research. To that end, information supporting where and what the business currently does is most helpful. Looking through https://www.sam.gov/sam/transcript/BPNSE_Extract%20Layout%20Level%200%20FOIA.pdf , most of the fields add value and should be saved. As far as how the users may want to search through the fields, I don't think we'll know until people start using it.

**Comment by dwcaraway** [comment]
Team decision: going with json-api format for now. can adjust later.

**Comment by dwcaraway** [comment]
Dave C to close this today with pull request merge

**Comment by catherinedevlin** [comment]
Should add some unit tests before moving to Done
