### ISSUE TITLE
Migrate SIBR-EZ's data backend to PostgreSQL

### ISSUE THREAD

**Issue by catherinedevlin** [18F/afsmallbiz#69]

**Comment by catherinedevlin** [comment]
Rather than migrate to the Postgres-specific `pg` adapter, I'm thinking of using a simple ORM - specifically, I like the look of massive.js.  Any objections?

**Comment by DavidEBest** [comment]
No big objections, if that looks like the good solution. It doesn't look like it is widely deployed, and I can't find much info on the web about it (aside from the gh readme, and an article about using it with mssql). Part of that could be the terrible package name, though. :)

**Comment by catherinedevlin** [comment]
I'm open to suggestions for other ORMs, too - I really don't know what's the gold standard in the node.js world (the way SQLAlchemy is for Python).  I grabbed massive mostly because it looked easy to understand.

**Comment by DavidEBest** [comment]
Based on some (very cursory) searches, it looks like Sequelize or node-orm2 are the most used. That said, I haven't used either of them. I'm fine with trying massive.
